// See the main shader file for copyright and other information.

// clang-format off
#pragma parameter VIRT_SCREEN_SETTINGS "=== Virtual Screen v1.0 settings ===" 0.0 0.0 1.0 1.0
#pragma parameter VIRT_SCREEN_CURVATURE "Curvature strength" 0.3 0.0 2.0 0.01
#pragma parameter VIRT_SCREEN_ZOOM "Zoom" 1.0 0.8 1.2 0.01
#pragma parameter VIRT_SCREEN_TILT_ANGLE "Vertical tilt" 0.0 -0.5 0.5 0.01
#pragma parameter VIRT_SCREEN_F "Focal Length" 1.4 0.0 10.0 0.1
// clang-format on
